### ISSUE TITLE
incomprehensible behavior

### ISSUE THREAD

**Issue by Phizilion** [v1a0/sqllex#17]
if there is one row in the table, and I want to display all the rows, I do not get a list of all rows, but when there are 2 or more rows in the table, then I get a list of these rows

**Comment by v1a0** [comment]
Hey @Phizilion, thanks for opened this issue.

Yeah, I'm absolutely agree with you, there have to be standard output with expected data type. 

Converting `[['some_val', ], ]` to `['some_val', ]` for select-like methods were experimental feature. I'm planning to remove it with the next update (v0.1.9+) today.

I'll notify you when release this update.

P.S.
As temporary "one hour" solution,  I suggest you make [instance checking](https://docs.python.org/3/library/functions.html#isinstance):
`if isinstance(data[0], list):`, where `data` is your is selected list or list[list] value.

Or just give me a few hours. and I'll fix it

**Comment by Phizilion** [comment]
> Or just give me a few hours. and I'll fix it

Well I'll wait.

**Comment by v1a0** [comment]
# Fixed since Sqllex version 0.1.9.0

```
pip install sqllex -U
```
