### ISSUE TITLE
WHERE argument to update

### ISSUE THREAD

**Issue by Phizilion** [v1a0/sqllex#18]
`WHERE` is a required argument for `update()`, although the absence of `WHERE` should change all rows in the table, that is, the `WRERE` argument should not be required and its absence should change all rows in the table

![2725_30 05 2021_15 06 48](https://user-images.githubusercontent.com/66277396/120103658-6115c980-c159-11eb-9b2b-d89cf0b16dd3.png)

P.S. at the moment such an opportunity is not necessary for me, but it may be needed by me or others in the future

**Comment by v1a0** [comment]
Thanks you, @Phizilion

Fixed this issue since sqllex [v0.1.9.1](https://github.com/v1a0/sqllex/releases/tag/v0.1.9.1)

```
pip install sqllex -U
```

**Comment by v1a0** [comment]
I'm really thankful for your contribution to development of this project ❤️ Added you to co-authors of v0.1.9.1 update

**Comment by Phizilion** [comment]
> I'm really thankful for your contribution to development of this project ❤️ Added you to co-authors of v0.1.9.1 update

oh thanks
