### ISSUE TITLE
FEATURE | UPDATE MANY

### ISSUE THREAD

**Issue by kingabzpro** [v1a0/sqllex#26]
## ✅ Describe your idea or issue
Let suppose I want to update the entire table or multiple rows of the table, do I just run the loop? I think we can create some sort of function where it updates multiple columns and rows.

**Comment by v1a0** [comment]
@kingabzpro how about use OR argument for insertmany method

```
db.insertmany('t4', many_values, OR=REPLACE)
```

I'm just don't really understand how to create update for many_values. Just because it'll overwrite each other. 

I realized it when I already coded it XD

Or each one list of values need some sort of pointer like 

```python
values = [
    ["name", "Alex", WHERE, 'id', 123],
    ["name", "Bon", WHERE, 'id', 321],
]

db.updatemany(
    'mytable',
    values
)
```

So I guess structure like this is kind of wired 😅

**Comment by kingabzpro** [comment]
```python
db.insertmany('table', many_values, OR=REPLACE)
```

This doesn't work.

**Comment by v1a0** [comment]
🤔 Strange..

**Comment by v1a0** [comment]
### FIXED (since v0.1.9.9)! 

So i fixed `.insertmany + OR=REPLACE` and added `.updatemany` method. Now you can use it like this:


```python
db.updatemany('t6', dataset)

# OR  

db.insertmany('t6', dataset, OR=REPLACE)
```

### Small speed test

```python
from time import time

db = SQLite3x(path='test.db')

db.connect()

db.create_table(
    't6',
    {
        'id': [INTEGER, UNIQUE, NOT_NULL],
        'val': [TEXT, DEFAULT, 'def_val']
    },
    IF_NOT_EXIST=True
)

data1 = [[x, 'hi'] for x in range(100_000)]
data2 = [[x, 'bye'] for x in range(100_000)]

t = time()

db.insertmany('t6', data1)

print(time() - t)  # 0.2731347084 sec - insert 100,000 values 


t = time()

db.insertmany('t6', data2, OR=REPLACE)

print(time() - t)  # 0.3724225811 sec - update 100,000 values 


t = time()

db.updatemany('t6', data2)

print(time() - t)  # 0.3598933219 sec - update 100,000 values 

```


Thank you, this issue revealed many other bugs of legacy versions that fixed now.

**Comment by kingabzpro** [comment]
Let me just update the article too.

**Comment by kingabzpro** [comment]
you don't have this? working?
![image](https://user-images.githubusercontent.com/36753484/122070647-94ba4a00-ce0f-11eb-8012-08aabea314a3.png)

**Comment by kingabzpro** [comment]
I am getting this error

![image](https://user-images.githubusercontent.com/36753484/122071162-f4185a00-ce0f-11eb-9d85-61f8f6c16d9f.png)

**Comment by kingabzpro** [comment]
I am going back to 0.1.9.6 this update is causing more problems

**Comment by v1a0** [comment]
I guess problem might be due to numpy.array() object

**Comment by v1a0** [comment]
### One more update, sqllex v0.1.9.10

```python
from numpy import array, nan
from sqllex import SQLite3x, TEXT, UNIQUE, INTEGER, REAL


data = array([['World', 2415712510, 318.1, '9.7%', nan],
              ['United States', 310645827, 949.5, '44.3%',
               'Johnson&Johnson, Moderna, Pfizer/BioNTech'],
              ['India', 252760364, 186.9, '3.5%',
               'Covaxin, Covishield, Oxford/AstraZeneca'],
              ['Brazil', 78906225, 376.7, '11.3%',
               'Oxford / AstraZeneca, Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac']])

vaccine_db = SQLite3x('numpy_test.db')

vaccine_db.create_table(
    name='Total',
    columns={
        "Country": [TEXT, UNIQUE],
        "Doses_Administered": INTEGER,
        "Doses_per_1000": REAL,
        "Fully_Vaccinated_Population": TEXT,
        "Vaccine_Type_Used": TEXT
    },
    IF_NOT_EXIST=True
)

vaccine_db.updatemany('Total', data)
```

![picture](https://raw.githubusercontent.com/v1a0/imgs/main/sqllex/issues/26_0.png)


#### Hopefully this is finally fixed now. Thanks for your patience.

**Comment by kingabzpro** [comment]
I have made an update and its working smooth [here](https://deepnote.com/@abid/Vaccine-Update-Dashboard-gybiCp-FTAyDgMjImOfj0w)
