### ISSUE TITLE
BUG | SQLite3xSearchCondition / SQLite3xColumn __and__, __or__

### ISSUE THREAD

**Issue by v1a0** [v1a0/sqllex#31]
I don't know why but it doesn't works with `and`, `or`, but works great with `|`, `&`. 

`urs_id: SQLite3xColumn` 

```python
(urs_id != 0) & (urs_id != 1) # works great
(urs_id = 0) | (urs_id = 1) # works great
```

```python
(urs_id != 0) and (urs_id != 1) # returns bullshit -  "urs_id <> 0"
(urs_id = 0) or (urs_id = 1) # returns bullshit - "urs_id = 1"
```

I'll open an issue about whit bug, but it's not really critical and necessary.

**Comment by asadafasab** [comment]
`__and__` Implements the `&` operator not `and` keyword.
`__or__` means  `|` not `or`.
(if that's what you meant)

**Comment by v1a0** [comment]
> `__and__` Implements the `&` operator not `and` keyword.
> `__or__` means  `|` not `or`.
> (if that's what you meant)

Not really, the problem is `or` and `|` returns different values


```python
print(
    (id_ < 2) or (id_ == 1)
)
# "('t1'.'id'=2)"
```

```python
print(
    (id_ < 2) | (id_ == 1)
)
# "(('t1'.'id'<2) OR ('t1'.'id'=1))"
```

**Comment by asadafasab** [comment]
```python
[1,2,3] and [3,2,1]
# [3, 2, 1]
[] and [3,2,1]
# []
[] or [3,2,1]
# [3, 2, 1]
"test" or "something"
# 'test'
bool([])
# False
False or True
# True
5 | 2
# 7
5 or 2
# 5
```
`or` and `|` are different type of operators.
I think that [this article](https://blog.finxter.com/python-and-operator-on-two-objects-or-lists-whats-the-result/) might be helpful.

**Comment by v1a0** [comment]
Wow, I didn't know. 

So is there exists some __method__ for class to override how `or` works for this class, like `__or__` method override instruction for `|` operator?

**Comment by asadafasab** [comment]
I do not think so.
