### ISSUE TITLE
BUG | SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by minibox161** [v1a0/sqllex#58]
## ✅ THE BUG 
I wrote the project and ran it on my main computer and everything works, but when I try to run this project on raspberrypi zero w I get an error (see below)

log:
```
File "/home/pi/.local/lib/python3.7/site-packages/sqllex/classes/__init__.py", line 5, in <module>
    from sqllex.core.entities.sqlite3x import *
  File "/home/pi/.local/lib/python3.7/site-packages/sqllex/core/entities/__init__.py", line 4, in <module>
    from sqllex.core.entities.sqlite3x import *
  File "/home/pi/.local/lib/python3.7/site-packages/sqllex/core/entities/sqlite3x/__init__.py", line 4, in <module>
    from sqllex.core.entities.sqlite3x.sqlite3x import *
  File "/home/pi/.local/lib/python3.7/site-packages/sqllex/core/entities/sqlite3x/sqlite3x.py", line 4, in <module>
    from sqllex.core.entities.abc import \
  File "/home/pi/.local/lib/python3.7/site-packages/sqllex/core/entities/abc/__init__.py", line 4, in <module>
    from sqllex.core.entities.abc.sql_database import AbstractDatabase, AbstractTable, AbstractColumn
...
File "<fstring>", line 1
    (SET=)
```

## ✅ CODE
```python
from sqllex import *
```

## ⚠️ CONFIGURATIONS
 - OS: [Raspbian GNU/Linux 10 (buster)]
 - Python version: [3.7.3]
 - Sqllex version: [0.2.0.3]

**Comment by v1a0** [comment]
Hey, @minibox16! Thanks for your report. 

Unfortunately, you have cut out a lot of information from the log, even the type of exception. So I can't pinpoint exactly what the problem was.

Found this on stackoverflow ["invalid syntax file "<fstring>", line 1"](https://stackoverflow.com/questions/49582183/pythonl-invalid-syntax-file-fstring-line-1), so guess you have to try another python version.

Please share your solution if you found it. 
Best regards, v1a0

**Comment by minibox161** [comment]
> Hey, @minibox16! Thanks for your report.
> 
> Unfortunately, you have cut out a lot of information from the log, even the type of exception. So I can't pinpoint exactly what the problem was.
> 
> Found this on stackoverflow ["invalid syntax file "", line 1"](https://stackoverflow.com/questions/49582183/pythonl-invalid-syntax-file-fstring-line-1), so guess you have to try another python version.
> 
> Please share your solution if you found it. Best regards, v1a0

I found solution
i just install python 3.9 )
